server:
  port: 9090
  todomvc-url: http://localhost:63342
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
logging:
  level:
    com.notbadcode: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
